[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>", "xyb@xyb.name"]
description = "An EPUB renderer for mdbook (xyb fork)."
name = "mdbook-epub"
version = "0.3.1-alpha.1"
readme = "README.md"
license = "MIT"
repository = "https://github.com/xieyubo/mdbook-epub"
documentation = "https://docs.rs/mdbook-epub"
keywords = ["epub", "mdbook", "documentation"]
categories = ["command-line-interface", "development-tools"]
edition = "2018"

[package.metadata.release]
sign-commit = true

[badges]
travis-ci = { repository = "Michael-F-Bryan/mdbook-epub", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "mdbook-epub"
doc = false

[dependencies]
epub-builder = "0.4"
failure = "0.1.1"
failure_derive = "0.1.1"
handlebars = "2.0"
lazy_static = "1.0"
pulldown-cmark = "0.5"
regex = "1.0.0"
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
mime_guess = "2.0"
env_logger = "0.6"
log = "0.4"
mdbook = "0.3.1"

[dev-dependencies]
tempdir = "0.3.5"
epub = "1.1.1"
